### ISSUE TITLE
[📚] Documentation Todo's

### ISSUE THREAD

**Issue by dylancom** [invertase/react-native-google-mobile-ads#15]
## Documentation Feedback

- [x] On iOS you need to ask for App Tracking permissions before requestion ads. 
I think the docs should mention something about recommending: https://github.com/zoontek/react-native-permissions
- [x] In a lot of packages is being reported that test ads don't display. 
This is due to AdMob requiring an extra entry in your app-ads.txt The docs should mention this: https://developers.google.com/admob/ios/test-ads
- [ ] On iOS14, you need to enable SKAdNetwork to track conversions. 
The docs could link to: https://developers.google.com/admob/ios/ios14 on how to update your info.plist to track conversions.

**Comment by mikehardy** [comment]
yes to all of these, in particular if it is a decision I certainly direct people to react-native-permissions, I collaborate there sometimes and it's a well-maintained easy-to-use library

**Comment by mattahorton** [comment]
Is ATT _required_? I thought AdMob allowed us to use just SKAdNetwork instead of IDFA?

**Comment by dylancom** [comment]
If you only want to show non-personalized ads it's not required.

**Comment by mattahorton** [comment]
> * SKAd

I really appreciate this straightforward response! Getting someone to say this directly is surprisingly difficult.
